# Generated by Django 4.1.7 on 2023-03-27 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_registration_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='image',
        ),
    ]
